// <auto-generated />
using System;
using DocSenseV1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocSenseV1.Migrations
{
    [DbContext(typeof(EFDatabaseContext))]
    partial class EFDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocSenseV1.Models.JobModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<double>("ExecutionTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("executionTimeMs");

                    b.Property<int>("FailedChunksCount")
                        .HasColumnType("integer")
                        .HasColumnName("failedChunksCount");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("planId");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<int>("ResultSymbolsCount")
                        .HasColumnType("integer")
                        .HasColumnName("resultSymbolsCount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SuccessfulChunksCount")
                        .HasColumnType("integer")
                        .HasColumnName("successfulChunksCount");

                    b.Property<int>("SymbolsCount")
                        .HasColumnType("integer")
                        .HasColumnName("symbolsCount");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer")
                        .HasColumnName("totalChunks");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.ToTable("Job", "public");
                });

            modelBuilder.Entity("DocSenseV1.Models.PlanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LimitRequests")
                        .HasColumnType("integer");

                    b.Property<long>("LimitSymbols")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LimitRequests = 100,
                            LimitSymbols = 100000L,
                            Type = "basic"
                        },
                        new
                        {
                            Id = 2,
                            LimitRequests = 1000,
                            LimitSymbols = 1000000L,
                            Type = "pro"
                        },
                        new
                        {
                            Id = 3,
                            LimitRequests = 10000,
                            LimitSymbols = 10000000L,
                            Type = "ultra"
                        });
                });

            modelBuilder.Entity("DocSenseV1.Models.UsageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("integer");

                    b.Property<long>("TotalSymbols")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "PlanId")
                        .IsUnique();

                    b.ToTable("Usage");
                });

            modelBuilder.Entity("DocSenseV1.Models.UsageModel", b =>
                {
                    b.HasOne("DocSenseV1.Models.PlanModel", "Plan")
                        .WithMany("Usages")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("DocSenseV1.Models.PlanModel", b =>
                {
                    b.Navigation("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
